server:
  port: 8765

spring:
    application:
        name: nextneo-api-gateway     
    #cloud:
        #gateway:
            #discovery:
                #locator:
                    #enabled: true
                    #lowerCaseServiceId: true
    sleuth:
        sampler:
            #1.0 -> tracking = 100% 0.2 -> tracking 20% transactions
            probability: 1.0
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
            