server:
  port: 8765

spring:
    application:
        name: nextneo-api-gateway     
    #cloud:
        #gateway:
            #discovery:
                #locator:
                    #enabled: true
                    #lowerCaseServiceId: true
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
            