server:
  port: 9595

spring:
    application:
        name: nextneo-limits-service
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: dev
    cloud:
        config:
            profile: dev
    sleuth:
        sampler:
            #1.0 -> tracking = 100% 0.2 -> tracking 20% transactions
            probability: 1.0

limits-service:
  minimum: 2
  maximum: 998