server:
  port: 8100

spring:
    application:
        name: nextneo-currency-conversion-service
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: dev
    cloud:
        config:
            profile: dev

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka