server:
  port: 8100

spring:
    application:
        name: nextneo-currency-conversion-service
    profiles:
        active: dev
    cloud:
        config:
            profile: dev
    sleuth:
        sampler:
            #1.0 -> tracking = 100% 0.2 -> tracking 20% transactions
            probability: 1.0

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
management:
    endpoint:
        health:
            probes:
                enabled: true
            livenessState:
                enabled: true
            readinessState:
                enabled: true 