server:
  port: 8000

spring:
    application:
        name: nextneo-currency-exchange-service
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: dev
    cloud:
        config:
            profile: dev