server:
  port: 8000

spring:
    application:
        name: nextneo-currency-exchange-service
    config:
        import: optional:configserver:http://localhost:8888
    profiles:
        active: dev
    cloud:
        config:
            profile: dev
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
resilience4j.retry:
    instances:
        sample-api:
            maxRetryAttempts: 5
            waitDuration: 1s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2