server:
  port: 8000

spring:
    application:
        name: nextneo-currency-exchange-service
    profiles:
        active: dev
    cloud:
        config:
            profile: dev
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
    sleuth:
        sampler:
            #1.0 -> tracking = 100% 0.2 -> tracking 20% transactions
            probability: 1.0

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
resilience4j.retry:
    instances:
        sample-api:
            maxRetryAttempts: 5
            waitDuration: 1s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            
management:
    endpoint:
        health:
            probes:
                enabled: true
            livenessState:
                enabled: true
            readinessState:
                enabled: true 